import { useEffect, useState } from "react";
import { FaBarcode, FaBoxes, FaDollarSign, FaImage, FaInfoCircle, FaSlidersH } from "react-icons/fa";
import { getCategories } from "../../services/categoryService";
import type { Category } from "../../types/Category";
import type { Product } from "../../types/Product";
import type { ProductErrors } from "../../validation/productValidation";
import ProductImageGallery from "./ProductImageGallery";

interface Props { product: Product; setProduct: React.Dispatch<React.SetStateAction<Product>>; errors: ProductErrors; saving: boolean; validateCurrentProduct: (product: Product) => void; }
const fieldClass = (error?: string) => `mt-2 w-full rounded-xl border bg-white px-4 py-3 text-slate-900 outline-none transition placeholder:text-slate-400 focus:ring-4 ${error ? "border-red-400 focus:border-red-500 focus:ring-red-500/10" : "border-slate-300 focus:border-blue-500 focus:ring-blue-500/10"}`;
const ErrorText = ({message}: {message?: string}) => message ? <p className="mt-1.5 text-xs font-medium text-red-600">{message}</p> : null;
const SectionTitle = ({icon: Icon, title, detail}: {icon: typeof FaInfoCircle; title: string; detail: string}) => <div className="mb-5 flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Icon/></span><div><h3 className="font-black text-slate-950">{title}</h3><p className="text-xs text-slate-500">{detail}</p></div></div>;

export default function ProductForm({product, setProduct, errors, saving, validateCurrentProduct}: Props) {
  const [categories, setCategories] = useState<Category[]>([]);
  const [categoryError, setCategoryError] = useState("");
  useEffect(() => { void getCategories().then((items) => setCategories(items.filter((item) => item.status === "active"))).catch(() => setCategoryError("Categories could not be loaded.")); }, []);
  const update = (changes: Partial<Product>) => { const next = {...product, ...changes}; setProduct(next); validateCurrentProduct(next); };
  const label = (text: string, required = false) => <>{text}{required && <span className="ml-1 text-red-500">*</span>}</>;

  return <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_22rem]">
    <div className="space-y-6">
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle icon={FaInfoCircle} title="Product information" detail="The details customers use to understand and find this item."/><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-800">{label("Product name", true)}<input value={product.name} disabled={saving} placeholder="e.g. Educational Robotics Kit" onChange={(e) => update({name: e.target.value})} className={fieldClass(errors.name)}/><ErrorText message={errors.name}/></label><label className="text-sm font-bold text-slate-800">{label("Brand", true)}<input value={product.brand} disabled={saving} placeholder="e.g. Books Bots Drones" onChange={(e) => update({brand: e.target.value})} className={fieldClass(errors.brand)}/><ErrorText message={errors.brand}/></label><label className="text-sm font-bold text-slate-800 md:col-span-2">{label("Description", true)}<textarea rows={5} value={product.description} disabled={saving} placeholder="Describe the product, its key features and who it is for..." onChange={(e) => update({description: e.target.value})} className={fieldClass(errors.description)}/><div className="flex justify-between"><ErrorText message={errors.description}/><span className="mt-1.5 text-xs font-medium text-slate-400">{product.description.length} characters</span></div></label><label className="text-sm font-bold text-slate-800 md:col-span-2">{label("Category", true)}<select value={product.category} disabled={saving || !!categoryError} onChange={(e) => update({category: e.target.value})} className={fieldClass(errors.category || categoryError)}><option value="">Select an active category</option>{categories.map((category) => <option key={category.id} value={category.name}>{category.name}</option>)}</select><ErrorText message={errors.category || categoryError}/></label></div></section>

      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle icon={FaDollarSign} title="Pricing" detail="Set customer price and internal cost for accurate margin reporting."/><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-800">{label("Selling price (ZAR)", true)}<div className="relative"><span className="absolute left-4 top-[1.15rem] text-sm text-slate-500">R</span><input type="number" min="0" step="0.01" value={product.price} disabled={saving} onChange={(e) => update({price: Number(e.target.value)})} className={`${fieldClass(errors.price)} pl-9`}/></div><ErrorText message={errors.price}/></label><label className="text-sm font-bold text-slate-800">Cost price (ZAR)<div className="relative"><span className="absolute left-4 top-[1.15rem] text-sm text-slate-500">R</span><input type="number" min="0" step="0.01" value={product.costPrice} disabled={saving} onChange={(e) => update({costPrice: Number(e.target.value)})} className={`${fieldClass(errors.costPrice)} pl-9`}/></div><ErrorText message={errors.costPrice}/></label></div>{product.price > 0 && product.costPrice >= 0 && <p className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Estimated gross margin: <strong>R {(product.price - product.costPrice).toFixed(2)}</strong></p>}</section>

      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><SectionTitle icon={FaBoxes} title="Inventory" detail="Stock, SKU and barcode can be added later."/><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-bold text-slate-800">Stock quantity<input type="number" min="0" value={product.stock} disabled={saving} onChange={(e) => update({stock: Number(e.target.value)})} className={fieldClass(errors.stock)}/><ErrorText message={errors.stock}/></label><label className="text-sm font-bold text-slate-800">Minimum stock alert<input type="number" min="0" value={product.minStock} disabled={saving} onChange={(e) => update({minStock: Number(e.target.value)})} className={fieldClass(errors.minStock)}/><ErrorText message={errors.minStock}/></label><label className="text-sm font-bold text-slate-800">SKU <span className="font-normal text-slate-400">(optional)</span><div className="relative"><FaBarcode className="absolute left-4 top-[1.2rem] text-slate-400"/><input value={product.sku} disabled={saving} placeholder="BBD-BOOK-001" onChange={(e) => update({sku: e.target.value.toUpperCase()})} className={`${fieldClass(errors.sku)} pl-11`}/></div><ErrorText message={errors.sku}/></label><label className="text-sm font-bold text-slate-800">Barcode <span className="font-normal text-slate-400">(optional)</span><input value={product.barcode} disabled={saving} inputMode="numeric" placeholder="Scan or enter barcode" onChange={(e) => update({barcode: e.target.value})} className={fieldClass(errors.barcode)}/><ErrorText message={errors.barcode}/></label></div></section>
    </div>

    <aside className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><SectionTitle icon={FaImage} title="Product gallery" detail="Add multiple views and choose the primary storefront image."/><ProductImageGallery images={product.images?.length ? product.images : product.imageUrl ? [product.imageUrl] : []} disabled={saving} onChange={(images) => update({images, imageUrl: images[0] || ""})}/><ErrorText message={errors.imageUrl}/></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><SectionTitle icon={FaSlidersH} title="Publishing" detail="Control storefront visibility and merchandising."/><label className="text-sm font-bold text-slate-800">Status<select value={product.status} disabled={saving} onChange={(e) => update({status: e.target.value as Product["status"]})} className={fieldClass(errors.status)}><option value="Active">Active — visible in store</option><option value="Hidden">Hidden — not visible</option></select><ErrorText message={errors.status}/></label><label className="mt-4 block text-sm font-bold text-slate-800">Homepage display order<input type="number" min="0" value={product.displayOrder} disabled={saving} onChange={(e) => update({displayOrder: Math.max(0, Number(e.target.value))})} className={fieldClass()}/><span className="mt-1 block text-xs font-normal text-slate-500">Lower numbers appear first.</span></label><div className="mt-5 space-y-3">{([{key: "featured", title: "Featured product", detail: "Highlight in the main featured section."}, {key: "isNew", title: "New arrival", detail: "Display in the New arrivals section."}, {key: "isBestSeller", title: "Best seller", detail: "Display in the Best sellers section."}, {key: "showWhenOutOfStock", title: "Show when out of stock", detail: "Keep the product discoverable when stock reaches zero."}] as const).map((option) => <label key={option.key} className="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4"><input type="checkbox" checked={Boolean(product[option.key])} disabled={saving} onChange={(e) => update({[option.key]: e.target.checked})} className="mt-1 h-4 w-4 accent-blue-600"/><span><span className="block text-sm font-bold text-slate-800">{option.title}</span><span className="mt-1 block text-xs text-slate-500">{option.detail}</span></span></label>)}</div></section></aside>
  </div>;
}
