import type { Order } from "../types/Order";

function formatDate(createdAt: any) {
  if (!createdAt) return "-";

  if (typeof createdAt.toDate === "function") {
    return createdAt.toDate().toLocaleDateString();
  }

  return new Date(createdAt).toLocaleDateString();
}

export function printOrders(orders: Order[]) {
  const popup = window.open("", "_blank");

  if (!popup) return;

  const totalRevenue = orders.reduce(
  (sum, order) => sum + order.totalAmount,
  0
);

const delivered = orders.filter(
  (o) => o.status === "delivered"
).length;

const pending = orders.filter(
  (o) =>
    o.status === "pending" ||
    o.status === "processing"
).length;

  popup.document.write(`
    <html>
      <head>
        <title>Orders Report</title>

        <style>

          body{
            font-family:Arial,sans-serif;
            padding:30px;
          }

          h1{
            margin-bottom:10px;
          }

         table{
  width:100%;
  border-collapse:collapse;
  margin-top:20px;
}

th,
td{
  border:1px solid #ccc;
  padding:10px;
  text-align:left;
}

th{
  background:#f3f4f6;
}

tbody tr:nth-child(even){
  background:#f9fafb;
}

        </style>

      </head>

      <body>

       <div style="margin-bottom:30px;">

  <h1
    style="
      margin:0;
      font-size:28px;
      color:#1e40af;
    "
  >
    Books & Bots
  </h1>

  <p
    style="
      margin:5px 0;
      color:#666;
    "
  >
    Order Management Report
  </p>

  <hr>

  <p>

    Generated:

    ${new Date().toLocaleString()}

  </p>


  
</div>



<div
  style="
    display:flex;
    gap:30px;
    margin-bottom:25px;
  "
>

  <div>

    <strong>Total Orders:</strong>

    ${orders.length}

  </div>

  <div>

    <strong>Pending:</strong>

    ${pending}

  </div>

  <div>

    <strong>Delivered:</strong>

    ${delivered}

  </div>

  <div>

    <strong>Revenue:</strong>

    R${totalRevenue.toFixed(2)}

  </div>

</div>

        <table>

          <thead>

            <tr>

              <th>Order ID</th>

              <th>Customer</th>

              <th>Status</th>

              <th>Total</th>

              <th>Date</th>

            </tr>

          </thead>

          <tbody>

            ${orders
              .map(
                (order) => `
                  <tr>

                    <td>${order.id ?? ""}</td>

                    <td>${order.customerName}</td>

                    <td>${order.status}</td>

                    <td>R${order.totalAmount.toFixed(2)}</td>

                    <td>${formatDate(order.createdAt)}</td>

                  </tr>
                `
              )
              .join("")}

          </tbody>

        </table>


        <div
  style="
    margin-top:40px;
    text-align:center;
    color:#888;
    font-size:12px;
  "
>

Generated by Books & Bots Admin ERP

</div>
      </body>

    </html>
  `);

  popup.document.close();

  popup.focus();

  popup.print();
}