import { useEffect, useState } from "react";
import { FaCheck, FaEnvelope, FaExclamationTriangle, FaLock, FaShieldAlt, FaTimes, FaUser } from "react-icons/fa";
import toast from "react-hot-toast";
import type { User, UserRole } from "../../types/User";

export default function EditUserModal({open, user, onClose, onSave}: {open: boolean; user: User | null; onClose: () => void; onSave: (user: User) => Promise<void>}) {
  const [role, setRole] = useState<UserRole>(user?.role ?? "customer"); const [saving, setSaving] = useState(false);
  useEffect(() => {if (user) setRole(user.role);}, [user]);
  useEffect(() => {if (!open) return; const previous=document.body.style.overflow;document.body.style.overflow="hidden";const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!saving)onClose();};window.addEventListener("keydown",escape);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",escape);};}, [open,onClose,saving]);
  if (!open || !user) return null;
  const changed = role !== user.role;
  const submit = async (event: React.FormEvent) => {event.preventDefault();if(!changed)return;try{setSaving(true);await onSave({...user,role});toast.success("User role updated");}catch(error){toast.error(error instanceof Error?error.message:"User role could not be updated");}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-3 backdrop-blur-sm sm:p-6" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)onClose();}}><form onSubmit={submit} role="dialog" aria-modal="true" aria-labelledby="edit-user-title" className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex items-center justify-between bg-gradient-to-r from-slate-950 to-blue-950 p-6 text-white"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Access management</p><h2 id="edit-user-title" className="mt-1 text-2xl font-black">Edit user role</h2></div><button type="button" onClick={onClose} disabled={saving} className="grid h-10 w-10 place-items-center rounded-xl hover:bg-white/10 disabled:opacity-50" aria-label="Close edit user"><FaTimes/></button></header>
    <div className="space-y-5 bg-slate-50/70 p-5 sm:p-7"><section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><FaUser/></span><div><p className="font-black text-slate-950">{`${user.firstName} ${user.lastName}`.trim()||"Unnamed user"}</p><p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><FaEnvelope/>{user.email}</p></div></div><div className="mt-4 flex items-start gap-3 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><FaLock className="mt-0.5 shrink-0"/><p>Name, email and phone are controlled by the customer’s authenticated profile. This panel only changes administrative access.</p></div></section>
      <section className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><FaShieldAlt/></span><div><h3 className="font-black">Account role</h3><p className="text-xs text-slate-500">Choose the level of access this account should receive.</p></div></div><div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>setRole("customer")} className={`rounded-xl border p-4 text-left transition ${role==="customer"?"border-blue-500 bg-blue-50 ring-4 ring-blue-500/10":"border-slate-200"}`}><strong className="block">Customer</strong><span className="mt-1 block text-xs text-slate-500">Can shop, manage orders, cart and wishlist.</span></button><button type="button" onClick={()=>setRole("admin")} className={`rounded-xl border p-4 text-left transition ${role==="admin"?"border-violet-500 bg-violet-50 ring-4 ring-violet-500/10":"border-slate-200"}`}><strong className="block">Administrator</strong><span className="mt-1 block text-xs text-slate-500">Can access and manage the admin panel.</span></button></div>{role==="admin"&&user.role!=="admin"&&<div className="mt-4 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800"><FaExclamationTriangle className="mt-0.5 shrink-0"/><p>Administrator access is powerful. Only grant it to a trusted team member.</p></div>}</section>
    </div><footer className="flex flex-col-reverse gap-3 border-t bg-white p-4 sm:flex-row sm:justify-end sm:px-6"><button type="button" onClick={onClose} disabled={saving} className="rounded-xl border border-slate-300 px-5 py-2.5 font-bold text-slate-700 hover:bg-slate-50">Cancel</button><button type="submit" disabled={saving||!changed} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"><FaCheck/>{saving?"Saving...":"Save role"}</button></footer></form></div>;
}
