import { useEffect } from "react";
import { FaCalendarAlt, FaCopy, FaEnvelope, FaPhone, FaReceipt, FaShieldAlt, FaTimes, FaWallet } from "react-icons/fa";
import toast from "react-hot-toast";
import type { User } from "../../types/User";
import { formatCurrency } from "../../utils/formatCurrency";

const fullName = (user: User) => `${user.firstName} ${user.lastName}`.trim() || "Unnamed user";
const initials = (user: User) => `${user.firstName?.[0] || ""}${user.lastName?.[0] || ""}`.toUpperCase() || "U";
const formatRegistered = (value: unknown) => {
  if (!value) return "Not recorded";
  const candidate = value as {toDate?: () => Date};
  const parsed = candidate.toDate ? candidate.toDate() : new Date(String(value));
  return Number.isNaN(parsed.getTime()) ? "Not recorded" : new Intl.DateTimeFormat("en-ZA", {dateStyle: "long"}).format(parsed);
};

export default function UserDetailsModal({open, user, onClose}: {open: boolean; user: User | null; onClose: () => void}) {
  useEffect(() => { if (!open) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; const escape = (event: KeyboardEvent) => {if (event.key === "Escape") onClose();}; window.addEventListener("keydown", escape); return () => {document.body.style.overflow = previous; window.removeEventListener("keydown", escape);}; }, [open, onClose]);
  if (!open || !user) return null;
  const copyId = async () => {if (!user.id) return; await navigator.clipboard.writeText(user.id); toast.success("User ID copied");};
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-3 backdrop-blur-sm sm:p-6" onMouseDown={(event) => {if (event.target === event.currentTarget) onClose();}}><div role="dialog" aria-modal="true" aria-labelledby="user-details-title" className="flex max-h-[92vh] w-full max-w-3xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl">
    <header className="flex items-center justify-between bg-gradient-to-r from-slate-950 to-blue-950 p-6 text-white"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Account profile</p><h2 id="user-details-title" className="mt-1 text-2xl font-black">User details</h2></div><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl text-slate-300 hover:bg-white/10 hover:text-white" aria-label="Close user details"><FaTimes/></button></header>
    <div className="flex-1 overflow-y-auto bg-slate-50/70 p-5 sm:p-7"><section className="flex flex-col gap-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-2xl bg-gradient-to-br from-blue-500 to-indigo-700 text-3xl font-black text-white shadow-lg">{user.avatar?<img src={user.avatar} alt={fullName(user)} className="h-full w-full object-cover"/>:initials(user)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h3 className="truncate text-2xl font-black text-slate-950">{fullName(user)}</h3><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${user.role === "admin" ? "bg-violet-100 text-violet-700" : "bg-blue-100 text-blue-700"}`}>{user.role}</span></div><p className="mt-2 flex items-center gap-2 text-sm text-slate-500"><FaEnvelope/>{user.email}</p>{user.phone&&<p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><FaPhone/>{user.phone}</p>}</div></section>
      <div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-600"><FaReceipt/></span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Total orders</p><p className="mt-1 text-3xl font-black">{user.totalOrders}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><FaWallet/></span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Paid spending</p><p className="mt-1 text-3xl font-black text-emerald-700">{formatCurrency(user.totalSpent)}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-50 text-violet-600"><FaShieldAlt/></span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Account access</p><p className="mt-1 font-black capitalize">{user.role}</p><p className="mt-1 text-xs text-slate-500">{user.role === "admin" ? "Can access administrative tools" : "Customer storefront access"}</p></div><div className="rounded-2xl border bg-white p-5 shadow-sm"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><FaCalendarAlt/></span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Registered</p><p className="mt-1 font-black">{formatRegistered(user.createdAt)}</p></div></div>
    </div><footer className="flex flex-col-reverse gap-3 border-t bg-white p-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><button onClick={() => void copyId()} disabled={!user.id} className="flex items-center gap-2 text-xs font-bold text-slate-500 disabled:opacity-40"><FaCopy/>Copy technical user ID</button><button onClick={onClose} className="rounded-xl bg-slate-900 px-5 py-2.5 font-bold text-white hover:bg-slate-800">Close</button></footer>
  </div></div>;
}
