import { FaEdit, FaEye, FaSort, FaSortDown, FaSortUp, FaTags, FaTrash } from "react-icons/fa";
import type { Category } from "../../types/Category";

interface Props { categories: Category[]; onView: (category: Category) => void; onEdit: (category: Category) => void; onDelete: (category: Category) => void; sortField: "name" | "productCount" | "status"; sortDirection: "asc" | "desc"; setSortField: React.Dispatch<React.SetStateAction<"name" | "productCount" | "status">>; setSortDirection: React.Dispatch<React.SetStateAction<"asc" | "desc">>; }
export default function CategoriesTable({categories, onView, onEdit, onDelete, sortField, sortDirection, setSortField, setSortDirection}: Props) {
  const sort = (field: Props["sortField"]) => { if (sortField === field) setSortDirection((current) => current === "asc" ? "desc" : "asc"); else {setSortField(field); setSortDirection("asc");} };
  const SortIcon = ({field}: {field: Props["sortField"]}) => <span className="ml-2 inline-flex text-slate-400">{sortField === field ? sortDirection === "asc" ? <FaSortUp/> : <FaSortDown/> : <FaSort/>}</span>;
  return <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full"><thead className="bg-slate-50"><tr><th><button onClick={() => sort("name")} className="inline-flex items-center font-bold">Category <SortIcon field="name"/></button></th><th>Storefront copy</th><th>Order</th><th><button onClick={() => sort("productCount")} className="inline-flex items-center font-bold">Products <SortIcon field="productCount"/></button></th><th><button onClick={() => sort("status")} className="inline-flex items-center font-bold">Status <SortIcon field="status"/></button></th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{categories.length === 0 ? <tr><td colSpan={6} className="py-14 text-center text-slate-500">No categories match the current filters.</td></tr> : categories.map((category) => <tr key={category.id}><td><div className="flex items-center gap-3">{category.image ? <img src={category.image} alt="" className="h-12 w-12 rounded-xl border border-slate-200 object-cover"/> : <span className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-400"><FaTags/></span>}<div><p className="font-bold text-slate-900">{category.name}</p>{category.showOnHomepage && <span className="text-xs font-bold text-blue-600">Homepage</span>}</div></div></td><td><p className="max-w-sm truncate text-sm text-slate-600" title={category.storefrontDescription}>{category.storefrontDescription || category.description}</p></td><td><span className="font-bold text-slate-800">{category.displayOrder}</span></td><td><span className="font-bold text-slate-800">{category.productCount}</span></td><td><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold capitalize ${category.status === "active" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-600"}`}>{category.status}</span></td><td><div className="flex justify-end gap-2"><button onClick={() => onView(category)} className="grid h-9 w-9 place-items-center rounded-lg border border-sky-200 bg-sky-50 text-sky-700 hover:bg-sky-100" aria-label={`View ${category.name}`} title="View"><FaEye/></button><button onClick={() => onEdit(category)} className="grid h-9 w-9 place-items-center rounded-lg border border-amber-200 bg-amber-50 text-amber-700 hover:bg-amber-100" aria-label={`Edit ${category.name}`} title="Edit"><FaEdit/></button><button onClick={() => onDelete(category)} className="grid h-9 w-9 place-items-center rounded-lg border border-red-200 bg-red-50 text-red-700 hover:bg-red-100" aria-label={`Delete ${category.name}`} title="Delete"><FaTrash/></button></div></td></tr>)}</tbody></table></div>;
}
