import { useEffect, useState } from "react";
import { FaCheck, FaEye, FaEyeSlash, FaTags, FaTimes } from "react-icons/fa";

export interface CategoryFormValue { name: string; description: string; status: "active" | "inactive"; }
interface Props { open: boolean; title: string; submitLabel: string; initialValue?: CategoryFormValue; onClose: () => void; onSave: (value: CategoryFormValue) => void | Promise<void>; }
const emptyValue: CategoryFormValue = {name: "", description: "", status: "active"};

export default function CategoryFormModal({open, title, submitLabel, initialValue, onClose, onSave}: Props) {
  const [value, setValue] = useState<CategoryFormValue>(initialValue ?? emptyValue);
  const [errors, setErrors] = useState<{name?: string; description?: string}>({});
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setValue(initialValue ?? emptyValue); setErrors({}); setSaving(false); } }, [initialValue, open]);
  useEffect(() => { const escape = (event: KeyboardEvent) => {if (event.key === "Escape" && !saving) onClose();}; window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [onClose, saving]);
  if (!open) return null;
  const validate = () => { const next: typeof errors = {}; if (value.name.trim().length < 2) next.name = "Enter a category name of at least 2 characters."; if (value.description.trim().length < 10) next.description = "Add a useful description of at least 10 characters."; setErrors(next); return Object.keys(next).length === 0; };
  const submit = async () => { if (!validate()) return; try { setSaving(true); await onSave({...value, name: value.name.trim(), description: value.description.trim()}); } finally { setSaving(false); } };
  const inputClass = (error?: string) => `mt-2 w-full rounded-xl border bg-white px-4 py-3 outline-none transition focus:ring-4 ${error ? "border-red-400 focus:border-red-500 focus:ring-red-500/10" : "border-slate-300 focus:border-blue-500 focus:ring-blue-500/10"}`;

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 p-3 backdrop-blur-sm sm:p-6" onMouseDown={(event) => {if (event.target === event.currentTarget && !saving) onClose();}}><div role="dialog" aria-modal="true" aria-labelledby="category-modal-title" className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl">
    <header className="flex items-center justify-between bg-gradient-to-r from-slate-950 to-blue-950 px-6 py-5 text-white"><div className="flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-400/15 text-cyan-300"><FaTags size={21}/></span><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">Catalogue structure</p><h2 id="category-modal-title" className="text-2xl font-black">{title}</h2></div></div><button onClick={onClose} disabled={saving} className="grid h-10 w-10 place-items-center rounded-xl text-slate-300 hover:bg-white/10 hover:text-white" aria-label="Close category form"><FaTimes/></button></header>
    <div className="space-y-6 bg-slate-50/70 p-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><label className="text-sm font-bold text-slate-800">Category name <span className="text-red-500">*</span><input autoFocus value={value.name} disabled={saving} maxLength={60} placeholder="e.g. Educational Drones" onChange={(e) => setValue({...value, name: e.target.value})} className={inputClass(errors.name)}/>{errors.name && <p className="mt-1.5 text-xs font-medium text-red-600">{errors.name}</p>}<span className="mt-1.5 block text-right text-xs text-slate-400">{value.name.length}/60</span></label><label className="mt-5 block text-sm font-bold text-slate-800">Description <span className="text-red-500">*</span><textarea rows={5} value={value.description} disabled={saving} maxLength={300} placeholder="Explain which products belong in this category..." onChange={(e) => setValue({...value, description: e.target.value})} className={inputClass(errors.description)}/>{errors.description && <p className="mt-1.5 text-xs font-medium text-red-600">{errors.description}</p>}<span className="mt-1.5 block text-right text-xs text-slate-400">{value.description.length}/300</span></label></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-800">Storefront visibility</p><p className="mt-1 text-xs text-slate-500">Inactive categories remain stored but cannot be assigned to new products.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setValue({...value, status: "active"})} className={`flex items-start gap-3 rounded-xl border p-4 text-left transition ${value.status === "active" ? "border-emerald-500 bg-emerald-50 ring-4 ring-emerald-500/10" : "border-slate-200 hover:border-slate-300"}`}><FaEye className="mt-0.5 text-emerald-600"/><span><strong className="block text-sm">Active</strong><span className="text-xs text-slate-500">Available in product forms</span></span></button><button type="button" onClick={() => setValue({...value, status: "inactive"})} className={`flex items-start gap-3 rounded-xl border p-4 text-left transition ${value.status === "inactive" ? "border-slate-500 bg-slate-100 ring-4 ring-slate-500/10" : "border-slate-200 hover:border-slate-300"}`}><FaEyeSlash className="mt-0.5 text-slate-600"/><span><strong className="block text-sm">Inactive</strong><span className="text-xs text-slate-500">Hidden from new products</span></span></button></div></section>
    </div><footer className="flex flex-col-reverse gap-3 border-t border-slate-200 bg-white px-6 py-4 sm:flex-row sm:justify-end"><button onClick={onClose} disabled={saving} className="rounded-xl border border-slate-300 px-5 py-2.5 font-bold text-slate-700 hover:bg-slate-50">Cancel</button><button onClick={() => void submit()} disabled={saving} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60"><FaCheck/>{saving ? "Saving..." : submitLabel}</button></footer>
  </div></div>;
}
