import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { FaBoxOpen, FaCheck, FaMoneyBillWave, FaTimes } from "react-icons/fa";
import { getReturnRequests, updateReturnRequest } from "../../services/returnService";
import type { ReturnRequest, ReturnStatus } from "../../types/ReturnRequest";

const style:Record<ReturnStatus,string>={requested:"bg-amber-100 text-amber-800",approved:"bg-blue-100 text-blue-700",rejected:"bg-red-100 text-red-700",received:"bg-violet-100 text-violet-700",refunded:"bg-emerald-100 text-emerald-700"};
export default function ReturnsPage(){const [records,setRecords]=useState<ReturnRequest[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [query,setQuery]=useState("");const [notes,setNotes]=useState<Record<string,string>>({});
const load=async()=>{try{setRecords(await getReturnRequests())}catch(e){toast.error(e instanceof Error?e.message:"Could not load returns")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
const filtered=useMemo(()=>records.filter(r=>`${r.orderId} ${r.uid} ${r.reason} ${r.status}`.toLowerCase().includes(query.toLowerCase())),[records,query]);
const act=async(r:ReturnRequest,status:ReturnStatus)=>{const labels:Partial<Record<ReturnStatus,string>>={rejected:"reject this return",received:"mark the returned goods as received",refunded:"confirm that the refund is completed"};if(labels[status]&&!window.confirm(`Are you sure you want to ${labels[status]}?`))return;try{setBusy(r.id);await updateReturnRequest(r.id,status,notes[r.id]);toast.success(status==="refunded"?"Refund marked completed.":`Return marked ${status}.`);await load()}catch(e){toast.error(e instanceof Error?e.message:"Could not update return")}finally{setBusy("")}};
return <div className="space-y-6"><header className="rounded-3xl bg-gradient-to-r from-slate-950 to-emerald-800 p-7 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">After-sales service</p><h1 className="mt-1 text-3xl font-black">Returns & refunds</h1><p className="mt-2 text-emerald-100">Review requests, receive returned goods, and record completed refunds.</p></header><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search order, customer, reason or status..." className="w-full rounded-xl border bg-white p-3 shadow-sm"/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<p className="p-12 text-center">Loading return requests...</p>:<div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Order / customer</th><th>Request</th><th>Status</th><th>Admin note</th><th>Controls</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><p className="font-mono text-xs font-bold">{r.orderId}</p><p className="mt-1 text-xs text-slate-500">Customer {r.uid.slice(0,10)}</p></td><td><p className="font-semibold text-slate-900">{r.reason}</p>{r.details&&<p className="mt-1 text-sm text-slate-500">{r.details}</p>}<p className="mt-1 text-xs text-slate-400">{new Date(r.requestedAt).toLocaleString("en-ZA")}</p></td><td><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${style[r.status]}`}>{r.status}</span>{r.refundStatus==="completed"&&<p className="mt-2 text-xs font-bold text-emerald-700">Refund completed</p>}</td><td><textarea value={notes[r.id]??r.adminNote??""} onChange={e=>setNotes({...notes,[r.id]:e.target.value})} placeholder="Optional decision note" className="min-h-16 min-w-52 rounded-xl border p-2 text-sm" disabled={busy===r.id}/></td><td><div className="flex min-w-56 flex-wrap gap-2">{r.status==="requested"&&<><button onClick={()=>void act(r,"approved")} disabled={!!busy} className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white"><FaCheck/>Approve</button><button onClick={()=>void act(r,"rejected")} disabled={!!busy} className="flex items-center gap-1 rounded-lg bg-red-600 px-3 py-2 text-xs font-bold text-white"><FaTimes/>Reject</button></>}{r.status==="approved"&&<button onClick={()=>void act(r,"received")} disabled={!!busy} className="flex items-center gap-1 rounded-lg bg-violet-600 px-3 py-2 text-xs font-bold text-white"><FaBoxOpen/>Mark Return Received</button>}{r.status==="received"&&<button onClick={()=>void act(r,"refunded")} disabled={!!busy} className="flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><FaMoneyBillWave/>Mark Refund Completed</button>}{["rejected","refunded"].includes(r.status)&&<span className="text-xs text-slate-500">Workflow complete</span>}</div></td></tr>)}</tbody></table>{filtered.length===0&&<p className="p-12 text-center text-slate-500">No return requests found.</p>}</div>}</div></div>}
