import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import { FaBullhorn, FaEdit, FaPlus, FaTimes } from "react-icons/fa";
import { getPromotions, savePromotion, setPromotionActive } from "../../services/promotionService";
import type { Promotion, PromotionInput } from "../../types/Promotion";

const blank: PromotionInput = {code:"", type:"percentage", value:10, minimumSpend:0, startsAt:"", endsAt:"", active:true};
const money = (value:number) => new Intl.NumberFormat("en-ZA",{style:"currency",currency:"ZAR"}).format(value);
const date = (value?:string) => value ? new Date(value).toLocaleDateString("en-ZA") : "No limit";

export default function PromotionsPage(){
  const [promotions,setPromotions]=useState<Promotion[]>([]); const [loading,setLoading]=useState(true);
  const [editing,setEditing]=useState<Promotion|null>(null); const [form,setForm]=useState<PromotionInput>(blank);
  const [open,setOpen]=useState(false); const [saving,setSaving]=useState(false); const [query,setQuery]=useState("");
  const load=async()=>{try{setPromotions(await getPromotions())}catch(e){toast.error(e instanceof Error?e.message:"Could not load promotions")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>promotions.filter(p=>p.code.toLowerCase().includes(query.toLowerCase())),[promotions,query]);
  const show=(promotion?:Promotion)=>{setEditing(promotion||null);setForm(promotion?{code:promotion.code,type:promotion.type,value:promotion.value,minimumSpend:promotion.minimumSpend,startsAt:promotion.startsAt||"",endsAt:promotion.endsAt||"",active:promotion.active}:blank);setOpen(true)};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();if(form.endsAt&&form.startsAt&&new Date(form.endsAt)<new Date(form.startsAt)){toast.error("End date must be after start date.");return}try{setSaving(true);await savePromotion({...form,code:form.code.trim().toUpperCase()},editing?.id);toast.success(editing?"Promotion updated.":"Promotion created.");setOpen(false);await load()}catch(error){toast.error(error instanceof Error?error.message:"Could not save promotion")}finally{setSaving(false)}};
  const toggle=async(p:Promotion)=>{try{await setPromotionActive(p,!p.active);toast.success(`Promotion ${p.active?"deactivated":"activated"}.`);await load()}catch(error){toast.error(error instanceof Error?error.message:"Could not update promotion")}};
  return <div className="space-y-6"><header className="flex flex-col gap-4 rounded-3xl bg-gradient-to-r from-slate-950 to-indigo-800 p-7 text-white sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-white/10 text-cyan-300"><FaBullhorn size={24}/></span><div><p className="text-xs font-bold uppercase tracking-[.18em] text-cyan-300">Sales tools</p><h1 className="text-3xl font-black">Promotions</h1><p className="mt-1 text-indigo-100">Create discount codes and control when customers can use them.</p></div></div><button onClick={()=>show()} className="flex items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-indigo-800"><FaPlus/>New promotion</button></header>
  <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search promotion code..." className="w-full rounded-xl border bg-white p-3 shadow-sm"/>
  <div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<p className="p-12 text-center">Loading promotions...</p>:<div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Code</th><th>Discount</th><th>Minimum spend</th><th>Validity</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td className="font-mono font-black text-slate-900">{p.code}</td><td>{p.type==="percentage"?`${p.value}%`:money(p.value)}</td><td>{money(p.minimumSpend)}</td><td><p>{date(p.startsAt)} – {date(p.endsAt)}</p></td><td><span className={`rounded-full px-3 py-1 text-xs font-bold ${p.active?"bg-emerald-100 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{p.active?"Active":"Inactive"}</span></td><td><div className="flex gap-2"><button onClick={()=>show(p)} className="rounded-lg border p-2" aria-label={`Edit ${p.code}`}><FaEdit/></button><button onClick={()=>void toggle(p)} className={`rounded-lg px-3 py-2 text-xs font-bold text-white ${p.active?"bg-slate-600":"bg-emerald-600"}`}>{p.active?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table>{filtered.length===0&&<p className="p-12 text-center text-slate-500">No promotions found.</p>}</div>}</div>
  {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-3" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setOpen(false)}}><form onSubmit={submit} className="w-full max-w-2xl overflow-hidden rounded-3xl bg-white shadow-2xl"><header className="flex justify-between bg-slate-950 p-6 text-white"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-300">Promotion editor</p><h2 className="text-2xl font-black">{editing?"Edit promotion":"Create promotion"}</h2></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close"><FaTimes/></button></header><div className="grid gap-4 p-6 sm:grid-cols-2"><label className="text-sm font-bold">Code *<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="mt-2 w-full rounded-xl border p-3" placeholder="SAVE10"/></label><label className="text-sm font-bold">Discount type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as PromotionInput["type"]})} className="mt-2 w-full rounded-xl border p-3"><option value="percentage">Percentage</option><option value="fixed">Fixed amount</option></select></label><label className="text-sm font-bold">Value *<input required min="0.01" step="0.01" type="number" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Minimum spend<input min="0" step="0.01" type="number" value={form.minimumSpend} onChange={e=>setForm({...form,minimumSpend:Number(e.target.value)})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Starts<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">Ends<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} className="mt-2 w-full rounded-xl border p-3"/></label><label className="flex items-center gap-2 text-sm font-bold sm:col-span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active and available to customers</label></div><footer className="flex justify-end gap-3 border-t p-5"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-5 py-3 font-bold">Cancel</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Saving...":"Save promotion"}</button></footer></form></div>}</div>
}
